### ISSUE TITLE
Prometheus gaps in data

### ISSUE THREAD

**Issue by micruzz82** [jenningsloy318/panos_exporter#1]
First off thank you for this code you have created. It's quite helpful to get metrics from palo alto firewalls.

I had an issue where I see gaps in prometheus graph

![image](https://user-images.githubusercontent.com/24628054/78418461-276c3000-7634-11ea-9d35-ed03d33c9fb1.png)

Would you be able to advise what I need to do to have a smooth graph?

Thanks
M

**Comment by micruzz82** [comment]
I dug more into this and I found at regular intervals the following errors.

1-
INFO[0106] Error getting Interface counter data, Get "": unsupported protocol scheme ""  source="interface_counter_collector.go:60"

2-
map[] map[] map[]

3-
INFO[0841] Error getting DataProcessor resource utilization data, No method specified  source="data_processor_resource_utilization_collector.go:58"

4-
INFO[1231] Error getting System resource utilization data, No method specified  source="system_resource_utilization_collector.go:59"

Any advice on how I can fix this please?

**Comment by jenningsloy318** [comment]
Hi @micruzz82, I will look into this issue ,can you please share the PA settings and other Prometheus config?
