### ISSUE TITLE
reverting zero metrics

### ISSUE THREAD

**Issue by inetman28** [jenningsloy318/panos_exporter#17]
hi,
I've noticed that sometimes panos_exporter reverts zero metrics

in first iteration:
```
curl http://pan-exporter.paloalto.local/panos\?target\=fw1.paloalto.local  | grep panos_session_session_pps
# HELP panos_session_session_pps Session info: packets per second
# TYPE panos_session_session_pps gauge
panos_session_session_pps{category="session",domain="statistics"} 950536
```

in following:
```
curl http://pan-exporter.paloalto.local/panos\?target\=fw1.paloalto.local  | grep panos_session_session_pps
# HELP panos_session_session_pps Session info: packets per second
# TYPE panos_session_session_pps gauge
panos_session_session_pps{category="session",domain="statistics"} 0
```

in grafana dashboard I see next picture 
![image](https://user-images.githubusercontent.com/45913745/199669259-056ad16d-ac52-438a-8a47-2ffcab2cf6ec.png)

that doesn't correlate to any kind of problem on device because the same "dashboard holes" I see on all devices with different platform

for example, another metric panos_global_counter_pkt_recv shows normal graph (without holes)
![image](https://user-images.githubusercontent.com/45913745/199669896-ff8f31f3-087b-4594-bda1-bbfdb872e08e.png)

**Comment by pawelos99** [comment]
I have also noticed this while using the exporter, the root cause is a race in the code when using goreqest. Pull requests waits for comments and approval.
