### ISSUE TITLE
Special characters in panos_exporter.yaml

### ISSUE THREAD

**Issue by JosephSonner** [jenningsloy318/panos_exporter#18]
If the password for the Palo Alto has special characters, the application tries to convert or interpret it as something different. 
For example !QAZ changes to %21QAZ - I have tried many different possibilities in the yaml including: 
password >
   !QAZ
"!QAZ"
'!QAZ"
\!QAZ

**Comment by pawelos99** [comment]
It was caused by missing url encoding when generating the api key. Fixed in pull request.

**Comment by zbbfufu** [comment]
Should be fixed now. I'll publish a new release to test it.
