### ISSUE TITLE
Releases and binaries

### ISSUE THREAD

**Issue by skorpy2009** [jenningsloy318/panos_exporter#2]
Hey,
great peace of software, thank you. Could you be so kind and setup binary builds via the CI?

**Comment by jenningsloy318** [comment]
Hi, this this what I want to do for a long time, as recently I don't have much time.


But if possible, contribution is welcome.

**Comment by jenningsloy318** [comment]
Hi @skorpy2009 since this exporter is not ready for proeuction, so I don't have a relaese. 

but if you can, just grab the code and build it 
```
make build
```

then you can see the binary under build directory
