### ISSUE TITLE
issue with PAN OS 9.0.9

### ISSUE THREAD

**Issue by Rookie852** [jenningsloy318/panos_exporter#3]
Hi, 
This application, has help us massively to capture metrics. We recently upgrade our firewall firmware to 9.0.0 release, and it stopped working.
get the following error: any ideas

goroutine 69 [running]:
github.com/jenningsloy318/panos_exporter/collector.(*SystemResourceUtilCollector).Collect(0xc0005c7260, 0xc00005e240)
	/root/go/src/github.com/jenningsloy318/panos_exporter/collector/system_resource_utilization_collector.go:72 +0xafe
github.com/jenningsloy318/panos_exporter/collector.(*PanosCollector).Collect.func1(0xc00023e750, 0xc00005e240, 0xae32c0, 0xc0005c7260)
	/root/go/src/github.com/jenningsloy318/panos_exporter/collector/panos_collector.go:93 +0x67
created by github.com/jenningsloy318/panos_exporter/collector.(*PanosCollector).Collect
	/root/go/src/github.com/jenningsloy318/panos_exporter/collector/panos_collector.go:91 +0x1bc

**Comment by jenningsloy318** [comment]
Hi, 
Glad to help with you, as from this log i can't find any information useful, but on the readme page, I listed all API calls used in this exporter, can you call these API calls with postman or curl ,and post all the  response, I doubt maybe some API path is changed after this upgrade, and also if possible to consult new API documents and try to find the new API calls and post them here. I will try to improve based on your findings.

**Comment by Rookie852** [comment]
Hi

I used postman, and tested all those API commands, and all seem to work without issues. So it's not the actual commands I would say, but response formatting is a bit different.

starting panos_exporter

root@ip-10-x-x-x:~/go/bin# ./panos_exporter --config.file=panos_exporter.yaml
INFO[0000] panos_exporter version , build reversion , build branch , build at  on host   source="main.go:67"
INFO[0000] Starting panos_exporter                       source="main.go:74"
INFO[0000] Loaded config file                            source="config.go:42"
INFO[0000] Listening on :9654                            source="main.go:99"
INFO[0005] Scraping target 10.x.x.x                      source="main.go:38"

panic: runtime error: index out of range [1] with length 1

goroutine 30 [running]:
github.com/jenningsloy318/panos_exporter/collector.(*SystemResourceUtilCollector).Collect(0xc0001a55c0, 0xc0001c8240)
	/root/go/src/github.com/jenningsloy318/panos_exporter/collector/system_resource_utilization_collector.go:72 +0xafe
github.com/jenningsloy318/panos_exporter/collector.(*PanosCollector).Collect.func1(0xc0001d4630, 0xc0001c8240, 0xae32c0, 0xc0001a55c0)
	/root/go/src/github.com/jenningsloy318/panos_exporter/collector/panos_collector.go:93 +0x67
created by github.com/jenningsloy318/panos_exporter/collector.(*PanosCollector).Collect
	/root/go/src/github.com/jenningsloy318/panos_exporter/collector/panos_collector.go:91 +0x1bc

--------
that’s the section for system_resource_utilization_collector.go 
or _, line := range topList {
 69                 if strings.Contains(line, "Cpu(s):") {
 70                         for _, cpuItem := range strings.Split(strings.Split(line, ":")[1], ",") {
 71                                 valueSlice := strings.Split(strings.TrimSpace(cpuItem), "%")
 72                                 cpuMetrics[valueSlice[1]] = valueSlice[0]
 73                         }
 74 
that’s the section for panos collector.go
func (p *PanosCollector) Collect(ch chan<- prometheus.Metric) {
 81         scrapeTime := time.Now()
 82 
 83         if p.panosClient != nil {
 84                 defer p.ctx.Done()
 85                 p.panosUp.Set(1)
 86                 wg := &sync.WaitGroup{}
 87                 wg.Add(len(p.collectors))
 88 
 89                 defer wg.Wait()
 90                 for _, collector := range p.collectors {
 91                         go func(collector prometheus.Collector) {
 92                                 defer wg.Done()
 93                                 collector.Collect(ch)
 94                         }(collector)
 95                 }
 96         } else {
 97                 p.panosUp.Set(0)
1:21


API response 8.1.11
-- working one from postman
<response status="success">
    <result>
        <![CDATA[top - 17:03:01 up 46 days, 46 min,  0 users,  load average: 5.47, 4.94, 4.62
Tasks: 159 total,   7 running, 151 sleeping,   0 stopped,   1 zombie
Cpu(s): 54.5%us,  1.4%sy,  0.7%ni, 43.4%id,  0.0%wa,  0.0%hi,  0.1%si,  0.0%st
Mem:   4119472k total,  3570940k used,   548532k free,   129196k buffers
Swap:  2008088k total,   117028k used,  1891060k free,  1367868k cached

API response 9.0.9
<response status="success">
    <result>
        <![CDATA[top - 17:03:38 up 4 days,  3:28,  0 users,  load average: 3.22, 3.03, 2.80
Tasks: 133 total,   3 running, 130 sleeping,   0 stopped,   0 zombie
%Cpu(s): 59.7 us,  2.7 sy,  1.9 ni, 35.3 id,  0.2 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem :  4119652 total,   361504 free,  1792564 used,  1965584 buff/cache
KiB Swap:     1972 total,     1972 free,        0 used.  1845516 avail Mem 

Possible hypothesis

old fomat for cpu:  Cpu(s): 54.5%us,  1.4%sy,  0.7%ni, 43.4%id,  0.0%wa,  0.0%hi,  0.1%si,  0.0%st
new format for cpu: 59.7 us,  2.7 sy,  1.9 ni, 35.3 id,  0.2 wa,  0.0 hi,  0.1 si,  0.0 st

do u think its something to do with this line.

Kind regards
Anu

**Comment by jenningsloy318** [comment]
Ok,seems here regex need to be adjusted, I will improve this ,will post you once there is update

**Comment by Rookie852** [comment]
compiled and all working again Thanks for your prompt response.
