### ISSUE TITLE
Issue with the exported content

### ISSUE THREAD

**Issue by a83r** [jenningsloy318/panos_exporter#4]
Hi,
I just found your exporter and it works great. What I found is that for several counters, that they aren't sorted by the instance but sorted by the rate. For example 

panos_global_counter_session_allocated

I just want an Grafana Chart how many Session are created per 5 Minutes, but I can't use rate on it because they aren't combinded by the instance?

**Comment by jenningsloy318** [comment]
Hi @a83r  

for all global counter metrics, I create them from batch that these metrics are extract from the response data, so it is impossible to configure individual one to add more labels for you purpose. 

but for further confirmation, you can post you global counter api response here, we can look into it then.

**Comment by a83r** [comment]
Hi @jenningsloy318 

firstly thanks for your great work with this exporter! I already found a solution for my problem: 
![Prom](https://user-images.githubusercontent.com/53919998/90225386-91ca8380-de11-11ea-89db-af37dbcdffa2.gif)
You can see that the Palo Alto API answers the calls already with a rate, because of that it isn't possible to rate and then sum the metric as Prometheus tries to group them by the rate and as well by the instance id.


![prom2](https://user-images.githubusercontent.com/53919998/90225391-92fbb080-de11-11ea-937c-6d287242167d.gif)

I just created a recording rule, which does a sum by instance. The then created recording rule is exactly what I needed.
On this metric I can use the rate function without any issues. 

Just another question, did you have timeout issues, as I seen some metrics are missing datapoints. 

Thanks for the great work!

**Comment by a83r** [comment]
Okay, sorry for bein a total noob. I just found out that it is possible to drop labels from metrics.

**Comment by jenningsloy318** [comment]
Awesome! 

Glad to hear that. And if you any other concerns regrading this exporeter, feel free to submit issues here.
